schedules:
- cron: "5 4 * * 1-5" # Run the pipeline daily at 4:05 AM UTC on weekdays
  displayName: Daily 4 AM Build
  branches:
    include:
      - main

trigger:
  branches:
    exclude:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cd SEAI_Dublin_25_03_24/Qa_Automation/Cypress_JavaScript
    npm install
  displayName: 'Install Dependencies'

- script: |
    npm run cy:run
  displayName: 'Run Cypress Tests'